# Generated by Django 2.2.24 on 2025-03-01 08:34

from django.db import migrations
from property.models import Flat


def change_new_building(apps, schema_editor):
    for flat in Flat.objects.all():
        flat.new_building = (flat.construction_year >= 2015)
        flat.save()


def undo_changes(apps, schema_editor):
    for flat in Flat.objects.all():
        flat.new_building = None
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(change_new_building, undo_changes)
    ]
