# Generated by Django 2.2.24 on 2025-03-01 09:49
import phonenumbers
from django.db import migrations


def convert_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        owner_phone_number = flat.owners_phonenumber
        parsed_phone_number = phonenumbers.parse(owner_phone_number, 'RU')

        if phonenumbers.is_valid_number(parsed_phone_number):
            converted_phone_number = phonenumbers.format_number(
                parsed_phone_number,
                phonenumbers.PhoneNumberFormat.E164)
            flat.owner_pure_phone = converted_phone_number
            flat.save(update_fields=['owner_pure_phone'])
        else:
            flat.owner_pure_phone = 'Необходимо ввести корректный номер!'
            flat.save(update_fields=['owner_pure_phone'])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(convert_phone_number)
    ]
