# Generated by Django 2.2.24 on 2025-03-01 10:11

from django.db import migrations


def move_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        owner = flat.owner
        owners_phonenumber = flat.owners_phonenumber
        owner_pure_phone = flat.owner_pure_phone

        Owner = apps.get_model('property', 'Owner')
        Owner.objects.get_or_create(
            owner=owner,
            owners_phonenumber=owners_phonenumber,
            owner_pure_phone=owner_pure_phone,
            defaults={
                'owner': owner,
                'owners_phonenumber': owners_phonenumber,
                'owner_pure_phone': owner_pure_phone
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(move_owners)
    ]
