# Generated by Django 2.2.24 on 2025-03-01 12:03

from django.db import migrations

def set_onwer_and_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    flats = Flat.objects.all()
    for flat in flats:
        flats_owner = Flat.objects.filter(owner=flat.owner)
        flat_ids = [flat_owner.id for flat_owner in flats_owner]

        owner, created = Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            defaults={
                "owner": flat.owner,
                "owners_phonenumber": flat.owners_phonenumber
        })
        owner.flats.set(flat_ids)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20250301_1311'),
    ]

    operations = [
        migrations.RunPython(set_onwer_and_flat)
    ]
